name: CI Deployment

on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Which envrionment to deploy?
        options: 
        - Development
        - Production
      commit:
        required: false
        type: string
        description: "[Optional] Deploy on which commit SHA?"

run-name: ${{ github.event_name == 'workflow_dispatch' && format('{0} | {1} | {2}', inputs.environment, inputs.commit || 'Latest', github.actor) || '' }}

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    if: inputs.environment == 'Development'
    steps:
      - run: echo "${{ inputs }}"
      - run: echo "Deployment is triggerd by ${{ github.triggering_actor }}"
      - run: echo "Commit hash is ${{ inputs.commit }}"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit || '' }}
          fetch-depth: 0
      - name: Get current branch
        id: current_branch
        run: echo "branch=$(git branch --show-current)" >> $GITHUB_OUTPUT
      - name: Validate branch
        run: echo "${{ steps.current_branch.outputs.branch }} ${{ GITHUB_REF }}"
      - name: Show Github SHA
        run: echo "github SHA ${{ github.sha }}"
      - name: List out all files
        run: ls -lrt
      - name: Install dependencies
        run: echo "Building ..."
      - name: Deploy
        run: echo "Deploying to DEV ..."

  deploy_prod:
    runs-on: ubuntu-latest
    if: inputs.environment == 'Production'
    steps:
      - run: echo "Deployment is triggerd by ${{ github.triggering_actor }}"
      - run: echo "Commit hash is ${{ inputs.commit }}"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit || '' }}
          fetch-depth: 0
      - name: Show head commit
        run: echo "Head commit ${{ format('{0} | {1}', github.event.head_commit.message, github.actor) || '' }}"
      - name: Show Github SHA
        run: echo "github SHA ${{ github.sha }}"
      - name: List out all files
        run: ls -lrt
      - name: Install dependencies
        run: echo "Building ..."
      - name: Deploy
        run: echo "Deploying to PROD ..."